# Site settings
title: "Beyond Big-O"
tagline: "from contest to codebase"
description: "Advanced competitive programming algorithms explained with rigorous mathematics and practical applications in software development."
baseurl: ""
url: "https://yourusername.github.io"

# Author
author:
  name: "Anirudh Singh"
  email: "anirudhsingh111100@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor/

# Math rendering
math_engine: mathjax
